[package]
name = "vibevoice-tts"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
candle-core.workspace = true
candle-nn.workspace = true
candle-transformers.workspace = true
thiserror.workspace = true
vibevoice-core = { path = "../vibevoice-core" }
vibevoice-tokenizer = { path = "../vibevoice-tokenizer" }

