[package]
name = "vibevoice-tokenizer"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
cuda = ["candle-core/cuda", "candle-nn/cuda", "vibevoice-core/cuda"]

[dependencies]
candle-core.workspace = true
candle-nn.workspace = true
thiserror.workspace = true
vibevoice-core = { path = "../vibevoice-core" }
